[phases.setup]
nixPkgs = ["jdk17", "maven", "nodejs_20"]

[phases.build]
cmds = [
  "cd control-pagos",
  "./mvnw clean package -DskipTests"
]

[start]
cmd = "cd control-pagos && java -jar target/control-pagos-0.0.1-SNAPSHOT.jar"
