[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -jar target/control-pagos-0.0.1-SNAPSHOT.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "web"

[services.variables]
PORT = "8080"
